### PR TITLE
Add ClassicPress icons to default ones

### PR DESCRIPTION
**Pull request by xxsimoxx**
This PR adds two icons, `feather` and `feather-coin` to the default icon set.

image

### CODE REVIEW

**Comment by joyously** [comment]
Why would we want to do this? What problem are you trying to solve?

Those icons don't belong in Tiny's default set. If they aren't already, they should be part of the CP dashicon file, which is loaded into the editor by default.
https://github.com/ClassicPress/ClassicPress-release/blob/0bf74d2f8a2abf35e91efec79e65454a520710e6/wp-includes/class-wp-editor.php#L992-L993

But I'm not sure why we would want to encourage anyone to use the CP logos for anything in the editor.

**Comment by xxsimoxx** [comment]
It could be useful for core plugins and like.

You know the editor structure much better than me.
If there is a better place to put them it's OK, but I worked on integrating menu icons in a plugin and seemed to me that in version 5 icons are handled in a very different way.

**Comment by joyously** [comment]
> It could be useful for core plugins and like.

This is not a reason to put these icons into Tiny's default.
The markup for the toolbars is different from 4.x to 5.x, but the syntax of how to specify icons in the function calls has not changed.
I don't see any reason to put these icons into CP at all, much less the editor. This is out of scope for this plugin.

**Comment by johnalarcon** [comment]
Yeah, these icons should go into the Dashicons set where the WordPress icon is held. By adding these as Dashicons, they would be accessible to core and 3rd party devs who want to use them. I thought this was in an issue at some point, but, I'm [not finding it](https://github.com/ClassicPress/ClassicPress/issues?q=dashicons) now. Maybe it was just forum or Slack discussion.

**Pull request closed without merging**
