### PR TITLE
Avoid dependence on jQuery

### PR DESCRIPTION
**Pull request by KTS915**
This replaces jQuery syntax with vanilla JavaScript

### CODE REVIEW

**Comment by joyously** [comment]
I'm sorry to have to break this to you, but this is wasted effort. The core scripts for the editor already depend on jQuery. This plugin is just a way to package the changes to test them. We aren't removing jQuery from core with this...

**Comment by KTS915** [comment]
Actually, it wasn't wasted effort. I suspected as much, but wanted to try out Github Desktop! But I would be interested in looking at the "core scripts" to see whether they are actually something to play with.

**Comment by KTS915** [comment]
Having just looked into this further, it appears that Tiny does not have any inherent dependence on jQuery, but it does have an integration plugin (included in this experimental plugin) that enables integration with jQuery. So I am wondering why we need to include that integration plugin. This seems to be a good time to start throwing off that linkage if we can.

**Comment by joyously** [comment]
Keep in mind that John threw together a very fragile thing that included everything you could possibly get in the download. His script doesn't even load it all. It's not how it would be added to core.

As for Tiny not depending on jQuery, it's because they rewrote most of it into Tiny. _It's bloated._

**Comment by johnalarcon** [comment]
@KTS915, I _believe_ the jQuery integration is useful for plugins that use jQuery in their dialogs, such as for showing/hiding one input based on the value of another. I can't confirm this, though; it could well be [conventional wisdom](https://www.google.com/search?q=conventional+wisdom).

@joyously, Even when the editor is chock-full of everything, it's still quite performant. The full zipped package is 785KB, which could be offset by removing v4 assets. The full install is 3.5MB when extracted on a site. I'm not seeing an issue with this. If you see this as problematic, can you elaborate on why?

**Comment by johnalarcon** [comment]
I'm not personally opposed to removing jQuery, but, think this falls outside the scope of this particular project. Removing the jQuery calls here and replacing them with vanilla JS would also introduce some minor inconsistency under the hood (presuming that the plugin will eventually be added to core.) I think that removing the jQuery dependency should be done as part of a larger, planned core project.

**Comment by KTS915** [comment]
> As for Tiny not depending on jQuery, it's because they rewrote most of it into Tiny. It's bloated.

That is quite irrelevant. This is not a forum for the merits or otherwise of jQuery but a place to organize how it is implemented as part of ClassicPress.

> I believe the jQuery integration is useful for plugins that use jQuery in their dialogs, such as for showing/hiding one input based on the value of another. I can't confirm this, though; it could well be conventional wisdom.

I am well aware of what conventional wisdom is. I'm a little older than you and might even have read Galbraith's book before you were born. What I can't understand is why we'd want to include the jQuery plugin as part of ClassicPress core. If it has the role you believe (and which I share) then it would seem more sensible to make it available as a stand-alone plugin for use by those who need it.

> Removing the jQuery calls here and replacing them with vanilla JS would also introduce some minor inconsistency under the hood (presuming that the plugin will eventually be added to core.) I think that removing the jQuery dependency should be done as part of a larger, planned core project.

That's just a recipe for making things harder later. I'm particularly surprised to see you make this argument, because you yourself often talk about avoiding technical debt.

I also find a it a little odd that you don't actually want to save yourselves time. Having tried these changes on my own local install, I can report (admittedly with some surprise) that they do speed up the time taken for Tiny to load. I like to save time wherever possible.

**Comment by johnalarcon** [comment]
Right. I didn't link "conventional wisdom" for you, necessarily... it was more for anyone who comes along later. But, come on...I'm 48 – you're not that much older than me. ;)

Regarding why keep jQuery: it's not going anywhere in ClassicPress in the foreseeable future and it has become ubiquitous in the *Press space. There's been a petition to replace jQuery with vanilla JS – which would be really amazing – but, it seems unlikely that anyone will take it on (due to the size and complexity of the task) or that it would get finished (for the same reasons.) For me, I don't really have strong feelings one way or the other about keeping the jQuery integration...but others do, particularly in terms of maintaining backward compatibility and providing something that devs can "hit the ground running" with.

Regarding technical debt: you're absolutely right, I'm an advocate. What I'm not an advocate for is doing it piece-meal without an overarching plan of action which doesn't really shed technical debt.

Regarding time/performance: with me, these are your best arguments and I would be curious to know the average difference in speed. If changing those few calls makes a substantial difference in the load time I'd be much more willing to make the change, not in an effort to remove tech debt (as I don't think that's what's happening) but to improve performance (which is something I advocate for.) Did you just refresh a few times, or did you benchmark it?

**Comment by joyously** [comment]
> But I would be interested in looking at the "core scripts" to see whether they are actually something to play with.

You can see them in wp-admin/js and wp-includes/js. There is a mixture of jQuery, vanilla, and Underscores used, especially in the Customizer. Backbone is in there sometimes too.

**Comment by KTS915** [comment]
@johnalarcon I'm 11 years older than you!

I didn't benchmark it. To be honest, I was just so surprised it made such a noticeable difference. But I'd be happy to do it if you can tell me the best way. Query Monitor? Inspector?

> Regarding technical debt: you're absolutely right, I'm an advocate. What I'm not an advocate for is doing it piece-meal without an overarching plan of action which doesn't really shed technical debt.

What I thought you would be an advocate for is not _adding_ to that debt burden. It seems odd to add to it now if we can easily avoid doing so, only to then be faced with trying to remove it later. Making that debt bigger actually makes it less likely to get removed too.

**Comment by johnalarcon** [comment]
I'm not actually sure the best way to benchmark an admin view. I suppose Query Monitor would be the best option.

You're right that I'm not fond of adding to the tech debt, and I do take your point. In this case, there were about 5 affected lines and the net result was actually more code, so, it wasn't highly compelling. As Joy noted, it's also outside the scope of the project.

I will note, however, that while this change will not be done under "removal of tech debt in CP," if benchmarks show results that can't be ignored, I will be happy to get it in under "improving performance of this particular plugin."

**Comment by joyously** [comment]
> Tiny does not have any inherent dependence on jQuery, but it does have an integration plugin (included in this experimental plugin) that enables integration with jQuery.

I've looked at the Tiny docs and code, and it seems that we don't need the integration. It's not a plugin, but if there is a choice in the download for Tiny without that component, choose that as the one to use.

**Comment by KTS915** [comment]
@johnalarcon Just tried benchmarking the difference with Query Monitor. With jQuery, the time taken between `DOMContentLoaded` and `load` was an average of a little over 4 seconds. With plain JavaScript, it was a little over 3.5 seconds.

As I said, I was surprised by this myself. I am guessing it's because four of the changes swap the function `.val()` for a property `.value`

**Comment by johnalarcon** [comment]
I think that's a worthy savings. I'm going to attempt to replicate your results and, if I can, I'll merge this.

**Comment by joyously** [comment]
> I'll merge this

Uh, isn't this in code that isn't needed now? I know this was a problem in WP, but have you tried the original issue since we changed the way the editor is loaded? Any fix for the original issue should go in core, not this plugin.

**Comment by johnalarcon** [comment]
Hahah... yeah, looking back over this, none of this code is even left in the plugin. :)

**Pull request closed without merging**
